apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - secrets.example.yaml
  - postgres.yaml
  - redpanda.yaml
  - jobs.yaml
  - ledger-api.yaml
  - workers.yaml
