// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notifier.sql

package notifierdb

import (
	"context"

	"github.com/google/uuid"
)

const insertInbox = `-- name: InsertInbox :execrows
INSERT INTO notifier.inbox (consumer, event_id) VALUES ($1, $2) ON CONFLICT DO NOTHING
`

type InsertInboxParams struct {
	Consumer string
	EventID  uuid.UUID
}

// 0 rows: this consumer already processed the event (a redelivery), so skip it.
func (q *Queries) InsertInbox(ctx context.Context, arg InsertInboxParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertInbox, arg.Consumer, arg.EventID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertNotification = `-- name: InsertNotification :exec
INSERT INTO notifier.notifications (id, event_id, partner_id, account_id, kind, amount_minor, account_seq)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type InsertNotificationParams struct {
	ID          uuid.UUID
	EventID     uuid.UUID
	PartnerID   uuid.UUID
	AccountID   uuid.UUID
	Kind        string
	AmountMinor int64
	AccountSeq  int64
}

func (q *Queries) InsertNotification(ctx context.Context, arg InsertNotificationParams) error {
	_, err := q.db.Exec(ctx, insertNotification,
		arg.ID,
		arg.EventID,
		arg.PartnerID,
		arg.AccountID,
		arg.Kind,
		arg.AmountMinor,
		arg.AccountSeq,
	)
	return err
}

const lastSeq = `-- name: LastSeq :one
SELECT last_seq FROM notifier.account_progress WHERE account_id = $1 FOR UPDATE
`

// The highest account_seq recorded for the account, locked for this transaction (0 rows for a new account).
func (q *Queries) LastSeq(ctx context.Context, accountID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, lastSeq, accountID)
	var last_seq int64
	err := row.Scan(&last_seq)
	return last_seq, err
}

const setLastSeq = `-- name: SetLastSeq :exec
INSERT INTO notifier.account_progress (account_id, last_seq) VALUES ($1, $2)
ON CONFLICT (account_id) DO UPDATE SET last_seq = greatest(notifier.account_progress.last_seq, excluded.last_seq)
`

type SetLastSeqParams struct {
	AccountID uuid.UUID
	LastSeq   int64
}

func (q *Queries) SetLastSeq(ctx context.Context, arg SetLastSeqParams) error {
	_, err := q.db.Exec(ctx, setLastSeq, arg.AccountID, arg.LastSeq)
	return err
}
