// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: relay.sql

package relaydb

import (
	"context"

	"github.com/google/uuid"
)

const markPublished = `-- name: MarkPublished :exec
UPDATE outbox SET published_at = now() WHERE id = ANY($1::uuid[]) AND published_at IS NULL
`

func (q *Queries) MarkPublished(ctx context.Context, ids []uuid.UUID) error {
	_, err := q.db.Exec(ctx, markPublished, ids)
	return err
}

const unpublished = `-- name: Unpublished :many
SELECT id, seq, account_id, payload FROM outbox WHERE published_at IS NULL ORDER BY seq LIMIT $1
`

type UnpublishedRow struct {
	ID        uuid.UUID
	Seq       *int64
	AccountID uuid.UUID
	Payload   []byte
}

// The next batch in publish order. No high-water mark: a lower seq on another account can commit after a higher
// one, and re-selecting from the start of the queue each cycle picks it up.
func (q *Queries) Unpublished(ctx context.Context, batchSize int32) ([]UnpublishedRow, error) {
	rows, err := q.db.Query(ctx, unpublished, batchSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UnpublishedRow
	for rows.Next() {
		var i UnpublishedRow
		if err := rows.Scan(
			&i.ID,
			&i.Seq,
			&i.AccountID,
			&i.Payload,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
