// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const insertAudit = `-- name: InsertAudit :exec
INSERT INTO audit_log (id, partner_id, actor, action, resource, status, request_id) VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type InsertAuditParams struct {
	ID        uuid.UUID
	PartnerID *uuid.UUID
	Actor     string
	Action    string
	Resource  string
	Status    int32
	RequestID string
}

func (q *Queries) InsertAudit(ctx context.Context, arg InsertAuditParams) error {
	_, err := q.db.Exec(ctx, insertAudit,
		arg.ID,
		arg.PartnerID,
		arg.Actor,
		arg.Action,
		arg.Resource,
		arg.Status,
		arg.RequestID,
	)
	return err
}
