// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: holds.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const dueHolds = `-- name: DueHolds :many
SELECT id FROM holds
WHERE status = 'active' AND expires_at <= now()
ORDER BY expires_at
LIMIT $1
`

// A batch of holds whose time is up. No lock here: each is then expired in its own short transaction.
func (q *Queries) DueHolds(ctx context.Context, batchSize int32) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, dueHolds, batchSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const endHold = `-- name: EndHold :one
UPDATE holds SET status = $2, captured_minor = $3, transaction_id = $4, ended_at = now()
WHERE id = $1
RETURNING id, partner_id, account_id, to_account_id, amount_minor, currency, status, expires_at, captured_minor, transaction_id, created_at, ended_at
`

type EndHoldParams struct {
	ID            uuid.UUID
	Status        string
	CapturedMinor int64
	TransactionID *uuid.UUID
}

func (q *Queries) EndHold(ctx context.Context, arg EndHoldParams) (Hold, error) {
	row := q.db.QueryRow(ctx, endHold,
		arg.ID,
		arg.Status,
		arg.CapturedMinor,
		arg.TransactionID,
	)
	var i Hold
	err := row.Scan(
		&i.ID,
		&i.PartnerID,
		&i.AccountID,
		&i.ToAccountID,
		&i.AmountMinor,
		&i.Currency,
		&i.Status,
		&i.ExpiresAt,
		&i.CapturedMinor,
		&i.TransactionID,
		&i.CreatedAt,
		&i.EndedAt,
	)
	return i, err
}

const hold = `-- name: Hold :one
SELECT id, partner_id, account_id, to_account_id, amount_minor, currency, status, expires_at, captured_minor, transaction_id, created_at, ended_at FROM holds WHERE id = $1 AND partner_id = $2
`

type HoldParams struct {
	ID        uuid.UUID
	PartnerID uuid.UUID
}

// Scoped to the partner: another partner's hold is not found.
func (q *Queries) Hold(ctx context.Context, arg HoldParams) (Hold, error) {
	row := q.db.QueryRow(ctx, hold, arg.ID, arg.PartnerID)
	var i Hold
	err := row.Scan(
		&i.ID,
		&i.PartnerID,
		&i.AccountID,
		&i.ToAccountID,
		&i.AmountMinor,
		&i.Currency,
		&i.Status,
		&i.ExpiresAt,
		&i.CapturedMinor,
		&i.TransactionID,
		&i.CreatedAt,
		&i.EndedAt,
	)
	return i, err
}

const insertHold = `-- name: InsertHold :one
INSERT INTO holds (id, partner_id, account_id, to_account_id, amount_minor, currency, expires_at)
VALUES ($1, $2, $3, $4, $5, $6, now() + make_interval(secs => $7::float8))
RETURNING id, partner_id, account_id, to_account_id, amount_minor, currency, status, expires_at, captured_minor, transaction_id, created_at, ended_at
`

type InsertHoldParams struct {
	ID               uuid.UUID
	PartnerID        uuid.UUID
	AccountID        uuid.UUID
	ToAccountID      uuid.UUID
	AmountMinor      int64
	Currency         string
	ExpiresInSeconds float64
}

// expires_at is computed on the database clock, like the idempotency lease.
func (q *Queries) InsertHold(ctx context.Context, arg InsertHoldParams) (Hold, error) {
	row := q.db.QueryRow(ctx, insertHold,
		arg.ID,
		arg.PartnerID,
		arg.AccountID,
		arg.ToAccountID,
		arg.AmountMinor,
		arg.Currency,
		arg.ExpiresInSeconds,
	)
	var i Hold
	err := row.Scan(
		&i.ID,
		&i.PartnerID,
		&i.AccountID,
		&i.ToAccountID,
		&i.AmountMinor,
		&i.Currency,
		&i.Status,
		&i.ExpiresAt,
		&i.CapturedMinor,
		&i.TransactionID,
		&i.CreatedAt,
		&i.EndedAt,
	)
	return i, err
}

const lockBalanceNoWait = `-- name: LockBalanceNoWait :one
SELECT account_id FROM balances WHERE account_id = $1 FOR UPDATE SKIP LOCKED
`

// The expiry job never waits for a busy account: if a transfer holds the balance row, the hold is expired on the
// next run instead (no client can capture it meanwhile, since it is past its time).
func (q *Queries) LockBalanceNoWait(ctx context.Context, accountID uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, lockBalanceNoWait, accountID)
	var account_id uuid.UUID
	err := row.Scan(&account_id)
	return account_id, err
}

const lockDueHold = `-- name: LockDueHold :one
SELECT id, partner_id, account_id, to_account_id, amount_minor, currency, status, expires_at, captured_minor, transaction_id, created_at, ended_at FROM holds WHERE id = $1 AND status = 'active' AND expires_at <= now() FOR UPDATE SKIP LOCKED
`

// Locks a hold for expiry, re-checking it is still active and due. SKIP LOCKED: a hold a request (or another
// replica) is ending right now is left to it.
func (q *Queries) LockDueHold(ctx context.Context, id uuid.UUID) (Hold, error) {
	row := q.db.QueryRow(ctx, lockDueHold, id)
	var i Hold
	err := row.Scan(
		&i.ID,
		&i.PartnerID,
		&i.AccountID,
		&i.ToAccountID,
		&i.AmountMinor,
		&i.Currency,
		&i.Status,
		&i.ExpiresAt,
		&i.CapturedMinor,
		&i.TransactionID,
		&i.CreatedAt,
		&i.EndedAt,
	)
	return i, err
}

const lockHold = `-- name: LockHold :one
SELECT h.id, h.partner_id, h.account_id, h.to_account_id, h.amount_minor, h.currency, h.status, h.expires_at, h.captured_minor, h.transaction_id, h.created_at, h.ended_at, (h.expires_at <= now())::bool AS expired FROM holds h WHERE h.id = $1 AND h.partner_id = $2 FOR UPDATE
`

type LockHoldParams struct {
	ID        uuid.UUID
	PartnerID uuid.UUID
}

type LockHoldRow struct {
	ID            uuid.UUID
	PartnerID     uuid.UUID
	AccountID     uuid.UUID
	ToAccountID   uuid.UUID
	AmountMinor   int64
	Currency      string
	Status        string
	ExpiresAt     pgtype.Timestamptz
	CapturedMinor int64
	TransactionID *uuid.UUID
	CreatedAt     pgtype.Timestamptz
	EndedAt       pgtype.Timestamptz
	Expired       bool
}

// Locks the hold first, then (separately, in account-id order) its accounts' balances: every path that ends a hold
// takes the hold row before any balance row, and balance rows always in id order, so no two paths can deadlock.
// expired says whether its time is up on the database clock.
func (q *Queries) LockHold(ctx context.Context, arg LockHoldParams) (LockHoldRow, error) {
	row := q.db.QueryRow(ctx, lockHold, arg.ID, arg.PartnerID)
	var i LockHoldRow
	err := row.Scan(
		&i.ID,
		&i.PartnerID,
		&i.AccountID,
		&i.ToAccountID,
		&i.AmountMinor,
		&i.Currency,
		&i.Status,
		&i.ExpiresAt,
		&i.CapturedMinor,
		&i.TransactionID,
		&i.CreatedAt,
		&i.EndedAt,
		&i.Expired,
	)
	return i, err
}
