// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: idempotency.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const claimKey = `-- name: ClaimKey :execrows
INSERT INTO idempotency (partner_id, key, request_hash, status, lease_token, locked_until)
VALUES ($1, $2, $3, 'in_progress', $4, now() + make_interval(secs => $5::float8))
ON CONFLICT DO NOTHING
`

type ClaimKeyParams struct {
	PartnerID    uuid.UUID
	Key          string
	RequestHash  []byte
	LeaseToken   *uuid.UUID
	LeaseSeconds float64
}

// The first request with a key claims it. ON CONFLICT DO NOTHING: if the key exists, 0 rows, and the caller reads it.
func (q *Queries) ClaimKey(ctx context.Context, arg ClaimKeyParams) (int64, error) {
	result, err := q.db.Exec(ctx, claimKey,
		arg.PartnerID,
		arg.Key,
		arg.RequestHash,
		arg.LeaseToken,
		arg.LeaseSeconds,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const cleanupKeys = `-- name: CleanupKeys :execrows
DELETE FROM idempotency
WHERE (partner_id, key) IN (
    SELECT i.partner_id, i.key FROM idempotency i
    WHERE (i.status = 'completed' AND i.completed_at < now() - make_interval(secs => $1::float8))
       OR (i.status = 'in_progress' AND i.locked_until < now() - make_interval(secs => $1::float8))
    LIMIT $2
    FOR UPDATE SKIP LOCKED
)
`

type CleanupKeysParams struct {
	RetentionSeconds float64
	BatchSize        int32
}

// One batch of expired keys: completed longer ago than the retention, or abandoned in progress that long.
// SKIP LOCKED: several replicas can run this at once without waiting on each other or on live requests.
func (q *Queries) CleanupKeys(ctx context.Context, arg CleanupKeysParams) (int64, error) {
	result, err := q.db.Exec(ctx, cleanupKeys, arg.RetentionSeconds, arg.BatchSize)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const completeKey = `-- name: CompleteKey :exec
UPDATE idempotency
SET status = 'completed', response_code = $4, response_body = $5, completed_at = now(), lease_token = NULL, locked_until = NULL
WHERE partner_id = $1 AND key = $2 AND lease_token = $3
`

type CompleteKeyParams struct {
	PartnerID    uuid.UUID
	Key          string
	LeaseToken   *uuid.UUID
	ResponseCode *int32
	ResponseBody []byte
}

func (q *Queries) CompleteKey(ctx context.Context, arg CompleteKeyParams) error {
	_, err := q.db.Exec(ctx, completeKey,
		arg.PartnerID,
		arg.Key,
		arg.LeaseToken,
		arg.ResponseCode,
		arg.ResponseBody,
	)
	return err
}

const fenceKey = `-- name: FenceKey :one
SELECT 1::int FROM idempotency
WHERE partner_id = $1 AND key = $2 AND lease_token = $3 AND status = 'in_progress'
FOR UPDATE
`

type FenceKeyParams struct {
	PartnerID  uuid.UUID
	Key        string
	LeaseToken *uuid.UUID
}

// The first statement of the ledger transaction: lock our own claim. No row means another attempt took over, so
// stop before touching money. Holding the lock until commit makes any takeover wait for us.
func (q *Queries) FenceKey(ctx context.Context, arg FenceKeyParams) (int32, error) {
	row := q.db.QueryRow(ctx, fenceKey, arg.PartnerID, arg.Key, arg.LeaseToken)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const keyState = `-- name: KeyState :one
SELECT request_hash, status, response_code, response_body, coalesce(locked_until > now(), false)::bool AS live
FROM idempotency WHERE partner_id = $1 AND key = $2
`

type KeyStateParams struct {
	PartnerID uuid.UUID
	Key       string
}

type KeyStateRow struct {
	RequestHash  []byte
	Status       string
	ResponseCode *int32
	ResponseBody []byte
	Live         bool
}

// A plain read (no lock): it never waits behind the attempt that holds the row.
func (q *Queries) KeyState(ctx context.Context, arg KeyStateParams) (KeyStateRow, error) {
	row := q.db.QueryRow(ctx, keyState, arg.PartnerID, arg.Key)
	var i KeyStateRow
	err := row.Scan(
		&i.RequestHash,
		&i.Status,
		&i.ResponseCode,
		&i.ResponseBody,
		&i.Live,
	)
	return i, err
}

const releaseKey = `-- name: ReleaseKey :execrows
DELETE FROM idempotency WHERE partner_id = $1 AND key = $2 AND lease_token = $3 AND status = 'in_progress'
`

type ReleaseKeyParams struct {
	PartnerID  uuid.UUID
	Key        string
	LeaseToken *uuid.UUID
}

// Frees a key after a failure, so a retry can run. Conditional: only our own claim, only while in progress. If the
// failure was a lost COMMIT acknowledgement, the row is already completed and stays; the retry gets the stored answer.
func (q *Queries) ReleaseKey(ctx context.Context, arg ReleaseKeyParams) (int64, error) {
	result, err := q.db.Exec(ctx, releaseKey, arg.PartnerID, arg.Key, arg.LeaseToken)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const takeOverKey = `-- name: TakeOverKey :execrows
UPDATE idempotency SET lease_token = $3, locked_until = now() + make_interval(secs => $4::float8)
WHERE partner_id = $1 AND key = $2 AND status = 'in_progress' AND locked_until <= now()
`

type TakeOverKeyParams struct {
	PartnerID    uuid.UUID
	Key          string
	LeaseToken   *uuid.UUID
	LeaseSeconds float64
}

// A new attempt takes over a claim whose lease has lapsed. If the lapsed attempt is still inside its ledger
// transaction, this waits on the row lock it holds, then re-checks: if that attempt completed, 0 rows.
func (q *Queries) TakeOverKey(ctx context.Context, arg TakeOverKeyParams) (int64, error) {
	result, err := q.db.Exec(ctx, takeOverKey,
		arg.PartnerID,
		arg.Key,
		arg.LeaseToken,
		arg.LeaseSeconds,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
