// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ledger.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const accountWithBalance = `-- name: AccountWithBalance :one
SELECT a.id, a.partner_id, a.kind, a.customer_ref, a.currency, a.status, a.min_balance_minor, a.created_at,
       b.posted_minor, b.held_minor, b.version
FROM accounts a JOIN balances b ON b.account_id = a.id
WHERE a.id = $1 AND a.partner_id = $2
`

type AccountWithBalanceParams struct {
	ID        uuid.UUID
	PartnerID uuid.UUID
}

type AccountWithBalanceRow struct {
	ID              uuid.UUID
	PartnerID       uuid.UUID
	Kind            string
	CustomerRef     *string
	Currency        string
	Status          string
	MinBalanceMinor int64
	CreatedAt       pgtype.Timestamptz
	PostedMinor     int64
	HeldMinor       int64
	Version         int64
}

// Scoped to the partner: another partner's account is simply not found (invariant 7).
func (q *Queries) AccountWithBalance(ctx context.Context, arg AccountWithBalanceParams) (AccountWithBalanceRow, error) {
	row := q.db.QueryRow(ctx, accountWithBalance, arg.ID, arg.PartnerID)
	var i AccountWithBalanceRow
	err := row.Scan(
		&i.ID,
		&i.PartnerID,
		&i.Kind,
		&i.CustomerRef,
		&i.Currency,
		&i.Status,
		&i.MinBalanceMinor,
		&i.CreatedAt,
		&i.PostedMinor,
		&i.HeldMinor,
		&i.Version,
	)
	return i, err
}

const applyToBalance = `-- name: ApplyToBalance :one
UPDATE balances
SET posted_minor = posted_minor + $2, held_minor = held_minor + $3, version = version + 1
WHERE account_id = $1
RETURNING posted_minor, held_minor, version
`

type ApplyToBalanceParams struct {
	AccountID   uuid.UUID
	PostedDelta int64
	HeldDelta   int64
}

type ApplyToBalanceRow struct {
	PostedMinor int64
	HeldMinor   int64
	Version     int64
}

// One ledger operation's change to one account: posted and held move together, and the version goes up by exactly
// one (a capture both releases the reservation and posts, as a single entry).
func (q *Queries) ApplyToBalance(ctx context.Context, arg ApplyToBalanceParams) (ApplyToBalanceRow, error) {
	row := q.db.QueryRow(ctx, applyToBalance, arg.AccountID, arg.PostedDelta, arg.HeldDelta)
	var i ApplyToBalanceRow
	err := row.Scan(&i.PostedMinor, &i.HeldMinor, &i.Version)
	return i, err
}

const closeAccount = `-- name: CloseAccount :exec
UPDATE accounts SET status = 'closed' WHERE id = $1
`

func (q *Queries) CloseAccount(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, closeAccount, id)
	return err
}

const insertAccount = `-- name: InsertAccount :exec
INSERT INTO accounts (id, partner_id, kind, customer_ref, currency, min_balance_minor)
VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertAccountParams struct {
	ID              uuid.UUID
	PartnerID       uuid.UUID
	Kind            string
	CustomerRef     *string
	Currency        string
	MinBalanceMinor int64
}

func (q *Queries) InsertAccount(ctx context.Context, arg InsertAccountParams) error {
	_, err := q.db.Exec(ctx, insertAccount,
		arg.ID,
		arg.PartnerID,
		arg.Kind,
		arg.CustomerRef,
		arg.Currency,
		arg.MinBalanceMinor,
	)
	return err
}

const insertBalance = `-- name: InsertBalance :exec
INSERT INTO balances (account_id) VALUES ($1)
`

func (q *Queries) InsertBalance(ctx context.Context, accountID uuid.UUID) error {
	_, err := q.db.Exec(ctx, insertBalance, accountID)
	return err
}

const insertPartner = `-- name: InsertPartner :exec
INSERT INTO partners (id, name, api_key_hash, rate_limit_per_min, funding_limit_minor)
VALUES ($1, $2, $3, $4, $5)
`

type InsertPartnerParams struct {
	ID                uuid.UUID
	Name              string
	ApiKeyHash        []byte
	RateLimitPerMin   int32
	FundingLimitMinor int64
}

func (q *Queries) InsertPartner(ctx context.Context, arg InsertPartnerParams) error {
	_, err := q.db.Exec(ctx, insertPartner,
		arg.ID,
		arg.Name,
		arg.ApiKeyHash,
		arg.RateLimitPerMin,
		arg.FundingLimitMinor,
	)
	return err
}

const insertPosting = `-- name: InsertPosting :exec
INSERT INTO postings (id, transaction_id, account_id, amount_minor, currency, account_seq, created_at)
VALUES ($1, $2, $3, $4, $5, $6, clock_timestamp())
`

type InsertPostingParams struct {
	ID            uuid.UUID
	TransactionID uuid.UUID
	AccountID     uuid.UUID
	AmountMinor   int64
	Currency      string
	AccountSeq    int64
}

// account_seq is the version AddToPosted just returned for this account. created_at is clock_timestamp() (when the
// row was written, after the lock wait) rather than now() (when the transaction began); it is only displayed.
func (q *Queries) InsertPosting(ctx context.Context, arg InsertPostingParams) error {
	_, err := q.db.Exec(ctx, insertPosting,
		arg.ID,
		arg.TransactionID,
		arg.AccountID,
		arg.AmountMinor,
		arg.Currency,
		arg.AccountSeq,
	)
	return err
}

const insertTransaction = `-- name: InsertTransaction :one
INSERT INTO transactions (id, partner_id, kind, reference) VALUES ($1, $2, $3, $4)
RETURNING created_at
`

type InsertTransactionParams struct {
	ID        uuid.UUID
	PartnerID uuid.UUID
	Kind      string
	Reference *string
}

func (q *Queries) InsertTransaction(ctx context.Context, arg InsertTransactionParams) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, insertTransaction,
		arg.ID,
		arg.PartnerID,
		arg.Kind,
		arg.Reference,
	)
	var created_at pgtype.Timestamptz
	err := row.Scan(&created_at)
	return created_at, err
}

const lockAccounts = `-- name: LockAccounts :many
SELECT a.id, a.partner_id, a.kind, a.currency, a.status, a.min_balance_minor,
       b.posted_minor, b.held_minor, b.version
FROM accounts a JOIN balances b ON b.account_id = a.id
WHERE a.id = ANY($1::uuid[]) AND a.partner_id = $2
ORDER BY a.id
FOR UPDATE OF b
`

type LockAccountsParams struct {
	Ids       []uuid.UUID
	PartnerID uuid.UUID
}

type LockAccountsRow struct {
	ID              uuid.UUID
	PartnerID       uuid.UUID
	Kind            string
	Currency        string
	Status          string
	MinBalanceMinor int64
	PostedMinor     int64
	HeldMinor       int64
	Version         int64
}

// Locks the balance rows of every account in a money movement, ALWAYS in account-id order. Two transfers between
// the same pair of accounts in opposite directions then take their locks in the same order, so neither can hold
// one lock while waiting for the other: no deadlock. (The sort happens before the locking step.)
// Scoped to the partner, so a request can never lock (and so slow down) another partner's account.
func (q *Queries) LockAccounts(ctx context.Context, arg LockAccountsParams) ([]LockAccountsRow, error) {
	rows, err := q.db.Query(ctx, lockAccounts, arg.Ids, arg.PartnerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LockAccountsRow
	for rows.Next() {
		var i LockAccountsRow
		if err := rows.Scan(
			&i.ID,
			&i.PartnerID,
			&i.Kind,
			&i.Currency,
			&i.Status,
			&i.MinBalanceMinor,
			&i.PostedMinor,
			&i.HeldMinor,
			&i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const outboxStatus = `-- name: OutboxStatus :one
SELECT count(*) AS total,
       count(*) FILTER (WHERE published_at IS NULL) AS unpublished,
       coalesce(extract(epoch FROM now() - min(created_at) FILTER (WHERE published_at IS NULL)), 0)::float8 AS oldest_unpublished_seconds
FROM outbox
`

type OutboxStatusRow struct {
	Total                    int64
	Unpublished              int64
	OldestUnpublishedSeconds float64
}

func (q *Queries) OutboxStatus(ctx context.Context) (OutboxStatusRow, error) {
	row := q.db.QueryRow(ctx, outboxStatus)
	var i OutboxStatusRow
	err := row.Scan(&i.Total, &i.Unpublished, &i.OldestUnpublishedSeconds)
	return i, err
}

const partnerByKeyHash = `-- name: PartnerByKeyHash :one
SELECT id, name, api_key_hash, rate_limit_per_min, funding_limit_minor FROM partners WHERE api_key_hash = $1
`

type PartnerByKeyHashRow struct {
	ID                uuid.UUID
	Name              string
	ApiKeyHash        []byte
	RateLimitPerMin   int32
	FundingLimitMinor int64
}

func (q *Queries) PartnerByKeyHash(ctx context.Context, apiKeyHash []byte) (PartnerByKeyHashRow, error) {
	row := q.db.QueryRow(ctx, partnerByKeyHash, apiKeyHash)
	var i PartnerByKeyHashRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ApiKeyHash,
		&i.RateLimitPerMin,
		&i.FundingLimitMinor,
	)
	return i, err
}

const rotatePartnerKey = `-- name: RotatePartnerKey :execrows
UPDATE partners SET api_key_hash = $2 WHERE id = $1
`

type RotatePartnerKeyParams struct {
	ID         uuid.UUID
	ApiKeyHash []byte
}

func (q *Queries) RotatePartnerKey(ctx context.Context, arg RotatePartnerKeyParams) (int64, error) {
	result, err := q.db.Exec(ctx, rotatePartnerKey, arg.ID, arg.ApiKeyHash)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const statement = `-- name: Statement :many
SELECT p.id, p.transaction_id, p.amount_minor, p.currency, p.account_seq, p.created_at, t.kind, t.reference
FROM postings p JOIN transactions t ON t.id = p.transaction_id
WHERE p.account_id = $1 AND p.account_seq > $2
ORDER BY p.account_seq
LIMIT $3
`

type StatementParams struct {
	AccountID uuid.UUID
	AfterSeq  int64
	PageSize  int32
}

type StatementRow struct {
	ID            uuid.UUID
	TransactionID uuid.UUID
	AmountMinor   int64
	Currency      string
	AccountSeq    int64
	CreatedAt     pgtype.Timestamptz
	Kind          string
	Reference     *string
}

// Keyset pagination: "the next page after account_seq n". Unlike OFFSET, it costs the same on page 1000 as on page 1,
// and rows added meanwhile can't shift a page. A sequence rather than a timestamp: account_seq is assigned under the
// account's lock, so it follows commit order by construction, whatever the clock does.
func (q *Queries) Statement(ctx context.Context, arg StatementParams) ([]StatementRow, error) {
	rows, err := q.db.Query(ctx, statement, arg.AccountID, arg.AfterSeq, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StatementRow
	for rows.Next() {
		var i StatementRow
		if err := rows.Scan(
			&i.ID,
			&i.TransactionID,
			&i.AmountMinor,
			&i.Currency,
			&i.AccountSeq,
			&i.CreatedAt,
			&i.Kind,
			&i.Reference,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
