// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Account struct {
	ID              uuid.UUID
	PartnerID       uuid.UUID
	Kind            string
	CustomerRef     *string
	Currency        string
	Status          string
	MinBalanceMinor int64
	CreatedAt       pgtype.Timestamptz
}

type Balance struct {
	AccountID   uuid.UUID
	PostedMinor int64
	HeldMinor   int64
	Version     int64
}

type Partner struct {
	ID                uuid.UUID
	Name              string
	ApiKeyHash        []byte
	RateLimitPerMin   int32
	FundingLimitMinor int64
	CreatedAt         pgtype.Timestamptz
}

type Posting struct {
	ID            uuid.UUID
	TransactionID uuid.UUID
	AccountID     uuid.UUID
	AmountMinor   int64
	Currency      string
	AccountSeq    int64
	CreatedAt     pgtype.Timestamptz
}

type Transaction struct {
	ID        uuid.UUID
	PartnerID uuid.UUID
	Kind      string
	Reference *string
	Status    string
	CreatedAt pgtype.Timestamptz
}
