// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Account struct {
	ID              uuid.UUID
	PartnerID       uuid.UUID
	Kind            string
	CustomerRef     *string
	Currency        string
	Status          string
	MinBalanceMinor int64
	CreatedAt       pgtype.Timestamptz
}

type AuditLog struct {
	ID        uuid.UUID
	PartnerID *uuid.UUID
	Actor     string
	Action    string
	Resource  string
	Status    int32
	RequestID string
	At        pgtype.Timestamptz
	Count     int32
	FirstAt   pgtype.Timestamptz
}

type Balance struct {
	AccountID   uuid.UUID
	PostedMinor int64
	HeldMinor   int64
	Version     int64
}

type Hold struct {
	ID            uuid.UUID
	PartnerID     uuid.UUID
	AccountID     uuid.UUID
	ToAccountID   uuid.UUID
	AmountMinor   int64
	Currency      string
	Status        string
	ExpiresAt     pgtype.Timestamptz
	CapturedMinor int64
	TransactionID *uuid.UUID
	CreatedAt     pgtype.Timestamptz
	EndedAt       pgtype.Timestamptz
}

type Idempotency struct {
	PartnerID    uuid.UUID
	Key          string
	RequestHash  []byte
	Status       string
	LeaseToken   *uuid.UUID
	LockedUntil  pgtype.Timestamptz
	ResponseCode *int32
	ResponseBody []byte
	CreatedAt    pgtype.Timestamptz
	CompletedAt  pgtype.Timestamptz
}

type NotifierAccountProgress struct {
	AccountID uuid.UUID
	LastSeq   int64
}

type NotifierInbox struct {
	Consumer    string
	EventID     uuid.UUID
	ProcessedAt pgtype.Timestamptz
}

type NotifierNotification struct {
	ID          uuid.UUID
	EventID     uuid.UUID
	PartnerID   uuid.UUID
	AccountID   uuid.UUID
	Kind        string
	AmountMinor int64
	AccountSeq  int64
	CreatedAt   pgtype.Timestamptz
}

type Outbox struct {
	ID          uuid.UUID
	Seq         *int64
	PartnerID   uuid.UUID
	AccountID   uuid.UUID
	AccountSeq  int64
	EventType   string
	Payload     []byte
	CreatedAt   pgtype.Timestamptz
	PublishedAt pgtype.Timestamptz
}

type Partner struct {
	ID                uuid.UUID
	Name              string
	ApiKeyHash        []byte
	RateLimitPerMin   int32
	FundingLimitMinor int64
	CreatedAt         pgtype.Timestamptz
}

type Posting struct {
	ID            uuid.UUID
	TransactionID uuid.UUID
	AccountID     uuid.UUID
	AmountMinor   int64
	Currency      string
	AccountSeq    int64
	CreatedAt     pgtype.Timestamptz
}

type Transaction struct {
	ID        uuid.UUID
	PartnerID uuid.UUID
	Kind      string
	Reference *string
	Status    string
	CreatedAt pgtype.Timestamptz
}
