// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: outbox.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const insertOutbox = `-- name: InsertOutbox :exec
INSERT INTO outbox (id, partner_id, account_id, account_seq, event_type, payload)
VALUES ($1, $2, $3, $4, $5, $6::jsonb || jsonb_build_object('occurred_at', clock_timestamp()))
`

type InsertOutboxParams struct {
	ID         uuid.UUID
	PartnerID  uuid.UUID
	AccountID  uuid.UUID
	AccountSeq int64
	EventType  string
	Payload    []byte
}

// Called right after the account's balance update in the same transaction: seq is drawn under the account lock.
// occurred_at comes from the database clock, like every other time the ledger records.
func (q *Queries) InsertOutbox(ctx context.Context, arg InsertOutboxParams) error {
	_, err := q.db.Exec(ctx, insertOutbox,
		arg.ID,
		arg.PartnerID,
		arg.AccountID,
		arg.AccountSeq,
		arg.EventType,
		arg.Payload,
	)
	return err
}
